version: '3.2'
services:
  app:
    restart: unless-stopped
    image: mosystems/dolibarr:10.0.3-debug
    environment:
      - DOLIBARR_SETUP_LANG=en_US
      - DOLIBARR_MAIN_URL=https://erp.mosystems.biz
      - DOLIBARR_DB_HOST=db
      - DOLIBARR_DB_NAME=dolibarr
      - DOLIBARR_DB_USER=dolibarr
      - DOLIBARR_DB_PASS=testpassword
      - DOLIBARR_DB_PORT=3306
      - DOLIBARR_FORCE_HTTPS=0
      - DOLIBARR_AUTH=dolibarr
      - DOLIBARR_ADMIN_USER=admin
      - DOLIBARR_ADMIN_PASS=admin
    volumes:
      - www:/www
      - documents:/documents
      # - ../modules:/www/custom
      - ./config/app/conf.php:/www/conf/conf.php:rw
      # - ./config/app/session.ini:/usr/local/etc/php/conf.d/session.ini:ro
      - ./config/app/dolibarr-install:/usr/local/bin/dolibarr-install:ro
      - ./config/app/docker-entrypoint:/usr/local/bin/docker-entrypoint:ro
      - sessions:/sessions
    depends_on: 
      - db
  
  web:
    image: nginx:stable
    volumes:
      - www:/www
      - ./config/web/dolibarr.conf:/etc/nginx/conf.d/default.conf:ro
      - ./config/web/fastcgi.conf:/etc/nginx/fastcgi.conf:ro
    ports: 
      - 9001:80
    depends_on: 
      - app

  db:
    image: mariadb:10.4
    environment:
      - MYSQL_DATABASE=dolibarr
      - MYSQL_USER=dolibarr
      - MYSQL_PASSWORD=testpassword
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      # - MYSQL_INITDB_SKIP_TZINFO=yes
    volumes:
      - database:/var/lib/mysql
    command: [
      '--character-set-server=utf8',
      '--collation-server=utf8_general_ci'
    ]

volumes:
  www:
  database:
  documents:
  sessions: