<?php
//
// File generated by Dolibarr installer 10.0.3 on Nov 29, 2019
//
// Take a look at conf.php.example file for an example of conf.php file
// and explanations for all possibles parameters.
//
$dolibarr_main_url_root=$_SERVER["DOLIBARR_MAIN_URL"];
$dolibarr_main_document_root='/www';
$dolibarr_main_url_root_alt='/custom';
$dolibarr_main_document_root_alt='/www/custom';
$dolibarr_main_data_root='/documents';
$dolibarr_main_db_host=$_SERVER["DOLIBARR_DB_HOST"];
$dolibarr_main_db_port=$_SERVER["DOLIBARR_DB_PORT"];
$dolibarr_main_db_name=$_SERVER["DOLIBARR_DB_NAME"];
$dolibarr_main_db_prefix='llx_';
$dolibarr_main_db_user=$_SERVER["DOLIBARR_DB_USER"];
$dolibarr_main_db_pass=$_SERVER["DOLIBARR_DB_PASS"];
$dolibarr_main_db_type='mysqli';
$dolibarr_main_db_character_set='utf8';
$dolibarr_main_db_collation='utf8_general_ci';
// Authentication settings
$dolibarr_main_authentication=$_SERVER["DOLIBARR_AUTH"] ?: "dolibarr";

//$dolibarr_main_demo='autologin,autopass';
// Security settings
$dolibarr_main_prod=(int) (bool) $_SERVER["DOLIBARR_PROD"];
$dolibarr_main_force_https=(int) (bool) $_SERVER["DOLIBARR_FORCE_HTTPS"];
$dolibarr_main_restrict_os_commands='mysqldump, mysql, pg_dump, pgrestore';
$dolibarr_nocsrfcheck=(int) (bool) $_SERVER["DOLIBARR_NOCSRF_CHECK"];
$dolibarr_main_instance_unique_id='e93d331b1e3068399d17f0f13c55931b';
$dolibarr_mailing_limit_sendbyweb='0';

//$dolibarr_lib_FPDF_PATH='';
//$dolibarr_lib_TCPDF_PATH='';
//$dolibarr_lib_FPDI_PATH='';
//$dolibarr_lib_TCPDI_PATH='';
//$dolibarr_lib_ADODB_PATH='';
//$dolibarr_lib_GEOIP_PATH='';
//$dolibarr_lib_NUSOAP_PATH='';
//$dolibarr_lib_PHPEXCEL_PATH='';
//$dolibarr_lib_ODTPHP_PATH='';
//$dolibarr_lib_ODTPHP_PATHTOPCLZIP='';
//$dolibarr_js_CKEDITOR='';
//$dolibarr_js_JQUERY='';
//$dolibarr_js_JQUERY_UI='';
//$dolibarr_js_JQUERY_FLOT='';

//$dolibarr_font_DOL_DEFAULT_TTF='';
//$dolibarr_font_DOL_DEFAULT_TTF_BOLD='';
