#!/bin/sh
set -e

DIR=/docker-entrypoint.d

if [ -d "$DIR" ]; then
    /bin/run-parts --verbose "$DIR"
fi

export XDEBUG_CONFIG='remote_enable=1 remote_autostart=1 remote_host=172.17.0.1'
if [ ! -e "/documents/install.lock" ]; then
    gosu www-data dolibarr-install
fi

# always update db configuration from environment variables
gosu www-data dolibarr-install dbupdate

exec docker-php-entrypoint "$@"