#!/usr/local/bin/php
<?php

global $conffile;

define('SYSLOG_FILE', 'php://stdout');

$test_fp = fopen(constant('SYSLOG_FILE'), 'a+');
fwrite($test_fp, 'TEST WRITE'.PHP_EOL);
fclose($test_fp);

function run_step($step) {
    global $conffile;
    global $langs, $conf;

    error_log(var_dump($_POST).PHP_EOL);

    ob_start();
    require $step;
    ob_end_clean();

    error_log('Conf.php location: '.$conffile.PHP_EOL);
}

error_log('Current dir: '.getcwd().PHP_EOL);
chdir('install');
$_POST['action'] = 'set';
$_POST['selectlang'] = $_SERVER['DOLIBARR_SETUP_LANG'];
$_POST['main_dir'] = '/www';
$_POST['main_data_dir'] = '/documents';
$_POST['main_url'] = $_SERVER['DOLIBARR_MAIN_URL'];
$_POST['db_user_root'] = '';
$_POST['db_pass_root'] = '';
$_POST['db_type'] = 'mysqli';
$_POST['db_host'] = $_SERVER['DOLIBARR_DB_HOST'];
$_POST['db_name'] = $_SERVER['DOLIBARR_DB_NAME'];
$_POST['db_user'] = $_SERVER['DOLIBARR_DB_USER'];
$_POST['db_pass'] = $_SERVER['DOLIBARR_DB_PASS'];
$_POST['db_port'] = $_SERVER['DOLIBARR_DB_PORT'];
$_POST['db_prefix'] = '';
$_POST['db_create_database'] = '';
$_POST['db_create_user'] = '';
$_POST['main_force_https'] = $_SERVER['DOLIBARR_FORCE_HTTPS'];
$_POST['main_use_alt_dir'] = 'on';
$_POST['main_alt_dir_name'] = 'custom';

run_step('./step1.php');
// Change generated conffile to suit our needs
$conffile_original = $conffile.'.original';
copy($conffile, $conffile_original);
$fp_conf_original = fopen($conffile_original, 'r');
$fp_conf = fopen($conffile, 'w');
while(!feof($fp_conf_original)) {
    $line = fgets($fp_conf_original);
    if (preg_match('/^\$dolibarr_main_db_pass/', $line)) {
        $line = '$dolibarr_main_db_pass=$_SERVER[\'DOLIBARR_DB_PASS\'];'.PHP_EOL;
    }
    if (preg_match('/^\$dolibarr_main_authentication/', $line)) {
        $line = '$dolibarr_main_authentication=!empty($_SERVER[\'DOLIBARR_AUTH\'])?$_SERVER[\'DOLIBARR_AUTH\']:\'dolibarr\''.PHP_EOL;
    }
    fputs($fp_conf, $line);
}
fclose($fp_conf_original);
// Add LDAP configuration
//fputs($fp_conf, ''.PHP_EOL);
fclose($fp_conf);

$_POST['login'] = !empty($_SERVER['DOLIBARR_ADMIN_USER']) ? $_SERVER['DOLIBARR_ADMIN_USER'] : 'admin';
$_POST['pass'] = $_POST['pass_verif'] = $_SERVER['DOLIBARR_ADMIN_PASS'];
$_POST['installlock'] = 1;
run_step('./step2.php');
// There is no step3.php in dolibarr
// step4.php is just a form, no need to run
run_step('./step5.php');